//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinstantPayDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankCurrency
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BankCurrency()
        {
            this.Funding = new HashSet<Funding>();
        }
    
        public int bankCcyId { get; set; }
        public Nullable<int> bankId { get; set; }
        public Nullable<int> ccyId { get; set; }
        public Nullable<int> wireInstId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual WireInstruction WireInstruction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Funding> Funding { get; set; }
    }
}
