//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinstantPayDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class SharedPhoto
    {
        public int ID { get; set; }
        public string PaymentId { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public bool IsViewed { get; set; }
        public string SharedPhotoId { get; set; }
        public string Comment { get; set; }
    }
}
