//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinstantPayDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Funding = new HashSet<Funding>();
        }
    
        public string username { get; set; }
        public string password { get; set; }
        public string KYCLink { get; set; }
        public Nullable<int> wlcMsgId { get; set; }
        public Nullable<System.DateTime> lastLoginDate { get; set; }
        public Nullable<bool> isLocal { get; set; }
        public Nullable<System.DateTime> curLoginDate { get; set; }
        public Nullable<int> roleId { get; set; }
        public Nullable<System.Guid> userIdByTSG { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string userMail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Funding> Funding { get; set; }
        public virtual Role Role { get; set; }
        public virtual WelcomeMessage WelcomeMessage { get; set; }
    }
}
