//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinstantPayDb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WinstantPayEntitiesEntities : DbContext
    {
        public WinstantPayEntitiesEntities()
            : base("name=WinstantPayEntitiesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnonimMail> AnonimMail { get; set; }
        public virtual DbSet<Bank> Bank { get; set; }
        public virtual DbSet<BankCurrency> BankCurrency { get; set; }
        public virtual DbSet<Conversion> Conversion { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Currency> Currency { get; set; }
        public virtual DbSet<DepartmentMails> DepartmentMails { get; set; }
        public virtual DbSet<EnumOfOrderStatuses> EnumOfOrderStatuses { get; set; }
        public virtual DbSet<FundChanges> FundChanges { get; set; }
        public virtual DbSet<Funding> Funding { get; set; }
        public virtual DbSet<Merchants> Merchants { get; set; }
        public virtual DbSet<OrdersHistory> OrdersHistory { get; set; }
        public virtual DbSet<ProofDoc> ProofDoc { get; set; }
        public virtual DbSet<ReferalLinksList> ReferalLinksList { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<SendedMails> SendedMails { get; set; }
        public virtual DbSet<SharedAdminLink> SharedAdminLink { get; set; }
        public virtual DbSet<SharedPhoto> SharedPhoto { get; set; }
        public virtual DbSet<SystemProperty> SystemProperty { get; set; }
        public virtual DbSet<TokenKeysForOrders> TokenKeysForOrders { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<WelcomeMessage> WelcomeMessage { get; set; }
        public virtual DbSet<WireInstruction> WireInstruction { get; set; }
        public virtual DbSet<ApiTokens> ApiTokens { get; set; }
        public virtual DbSet<FavoritesCurrencies> FavoritesCurrencies { get; set; }
    
        public virtual int AddAnonimMailRec(string mailFrom, string mailSubject, string mailNotes, string userIpInRequest, string browserName, string browserVersion, Nullable<bool> isMobile)
        {
            var mailFromParameter = mailFrom != null ?
                new ObjectParameter("MailFrom", mailFrom) :
                new ObjectParameter("MailFrom", typeof(string));
    
            var mailSubjectParameter = mailSubject != null ?
                new ObjectParameter("MailSubject", mailSubject) :
                new ObjectParameter("MailSubject", typeof(string));
    
            var mailNotesParameter = mailNotes != null ?
                new ObjectParameter("MailNotes", mailNotes) :
                new ObjectParameter("MailNotes", typeof(string));
    
            var userIpInRequestParameter = userIpInRequest != null ?
                new ObjectParameter("UserIpInRequest", userIpInRequest) :
                new ObjectParameter("UserIpInRequest", typeof(string));
    
            var browserNameParameter = browserName != null ?
                new ObjectParameter("BrowserName", browserName) :
                new ObjectParameter("BrowserName", typeof(string));
    
            var browserVersionParameter = browserVersion != null ?
                new ObjectParameter("BrowserVersion", browserVersion) :
                new ObjectParameter("BrowserVersion", typeof(string));
    
            var isMobileParameter = isMobile.HasValue ?
                new ObjectParameter("IsMobile", isMobile) :
                new ObjectParameter("IsMobile", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddAnonimMailRec", mailFromParameter, mailSubjectParameter, mailNotesParameter, userIpInRequestParameter, browserNameParameter, browserVersionParameter, isMobileParameter);
        }
    
        public virtual int AddBank(string bankName, Nullable<int> bankCountry, ObjectParameter bankId)
        {
            var bankNameParameter = bankName != null ?
                new ObjectParameter("bankName", bankName) :
                new ObjectParameter("bankName", typeof(string));
    
            var bankCountryParameter = bankCountry.HasValue ?
                new ObjectParameter("bankCountry", bankCountry) :
                new ObjectParameter("bankCountry", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddBank", bankNameParameter, bankCountryParameter, bankId);
        }
    
        public virtual int AddBankCurrency(Nullable<int> bankId, Nullable<int> ccyId, Nullable<int> wireInstId)
        {
            var bankIdParameter = bankId.HasValue ?
                new ObjectParameter("bankId", bankId) :
                new ObjectParameter("bankId", typeof(int));
    
            var ccyIdParameter = ccyId.HasValue ?
                new ObjectParameter("ccyId", ccyId) :
                new ObjectParameter("ccyId", typeof(int));
    
            var wireInstIdParameter = wireInstId.HasValue ?
                new ObjectParameter("wireInstId", wireInstId) :
                new ObjectParameter("wireInstId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddBankCurrency", bankIdParameter, ccyIdParameter, wireInstIdParameter);
        }
    
        public virtual int AddBankCurrencyGetId(Nullable<int> bankId, Nullable<int> ccyId, Nullable<int> wireInstId, ObjectParameter bankCcyId)
        {
            var bankIdParameter = bankId.HasValue ?
                new ObjectParameter("bankId", bankId) :
                new ObjectParameter("bankId", typeof(int));
    
            var ccyIdParameter = ccyId.HasValue ?
                new ObjectParameter("ccyId", ccyId) :
                new ObjectParameter("ccyId", typeof(int));
    
            var wireInstIdParameter = wireInstId.HasValue ?
                new ObjectParameter("wireInstId", wireInstId) :
                new ObjectParameter("wireInstId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddBankCurrencyGetId", bankIdParameter, ccyIdParameter, wireInstIdParameter, bankCcyId);
        }
    
        public virtual int AddBankDeposit(Nullable<decimal> fndAmt, string username, Nullable<int> bankCcyId, ObjectParameter insId)
        {
            var fndAmtParameter = fndAmt.HasValue ?
                new ObjectParameter("fndAmt", fndAmt) :
                new ObjectParameter("fndAmt", typeof(decimal));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var bankCcyIdParameter = bankCcyId.HasValue ?
                new ObjectParameter("bankCcyId", bankCcyId) :
                new ObjectParameter("bankCcyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddBankDeposit", fndAmtParameter, usernameParameter, bankCcyIdParameter, insId);
        }
    
        public virtual int AddContactUsRec(string departmentName, string departmentMail, Nullable<int> departmentWeight)
        {
            var departmentNameParameter = departmentName != null ?
                new ObjectParameter("DepartmentName", departmentName) :
                new ObjectParameter("DepartmentName", typeof(string));
    
            var departmentMailParameter = departmentMail != null ?
                new ObjectParameter("DepartmentMail", departmentMail) :
                new ObjectParameter("DepartmentMail", typeof(string));
    
            var departmentWeightParameter = departmentWeight.HasValue ?
                new ObjectParameter("DepartmentWeight", departmentWeight) :
                new ObjectParameter("DepartmentWeight", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddContactUsRec", departmentNameParameter, departmentMailParameter, departmentWeightParameter);
        }
    
        public virtual int AddCurrency(Nullable<int> ccyId, string ccyCode, string ccyName, string ccySymbol, ObjectParameter ccyOutId)
        {
            var ccyIdParameter = ccyId.HasValue ?
                new ObjectParameter("ccyId", ccyId) :
                new ObjectParameter("ccyId", typeof(int));
    
            var ccyCodeParameter = ccyCode != null ?
                new ObjectParameter("ccyCode", ccyCode) :
                new ObjectParameter("ccyCode", typeof(string));
    
            var ccyNameParameter = ccyName != null ?
                new ObjectParameter("ccyName", ccyName) :
                new ObjectParameter("ccyName", typeof(string));
    
            var ccySymbolParameter = ccySymbol != null ?
                new ObjectParameter("ccySymbol", ccySymbol) :
                new ObjectParameter("ccySymbol", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddCurrency", ccyIdParameter, ccyCodeParameter, ccyNameParameter, ccySymbolParameter, ccyOutId);
        }
    
        public virtual int AddFavoritesCurrency(string iDUser, string iDCurrencies)
        {
            var iDUserParameter = iDUser != null ?
                new ObjectParameter("IDUser", iDUser) :
                new ObjectParameter("IDUser", typeof(string));
    
            var iDCurrenciesParameter = iDCurrencies != null ?
                new ObjectParameter("IDCurrencies", iDCurrencies) :
                new ObjectParameter("IDCurrencies", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddFavoritesCurrency", iDUserParameter, iDCurrenciesParameter);
        }
    
        public virtual int AddFundHistoryRec(Nullable<int> fundId, Nullable<int> userId, Nullable<System.DateTime> changingDate, string oldStatus, string newStatus, string adminNote)
        {
            var fundIdParameter = fundId.HasValue ?
                new ObjectParameter("fundId", fundId) :
                new ObjectParameter("fundId", typeof(int));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            var changingDateParameter = changingDate.HasValue ?
                new ObjectParameter("changingDate", changingDate) :
                new ObjectParameter("changingDate", typeof(System.DateTime));
    
            var oldStatusParameter = oldStatus != null ?
                new ObjectParameter("oldStatus", oldStatus) :
                new ObjectParameter("oldStatus", typeof(string));
    
            var newStatusParameter = newStatus != null ?
                new ObjectParameter("newStatus", newStatus) :
                new ObjectParameter("newStatus", typeof(string));
    
            var adminNoteParameter = adminNote != null ?
                new ObjectParameter("adminNote", adminNote) :
                new ObjectParameter("adminNote", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddFundHistoryRec", fundIdParameter, userIdParameter, changingDateParameter, oldStatusParameter, newStatusParameter, adminNoteParameter);
        }
    
        public virtual int AddHistorycalDataFromOrders(Nullable<int> merchantId, Nullable<System.Guid> orderToken, Nullable<int> status, string comment)
        {
            var merchantIdParameter = merchantId.HasValue ?
                new ObjectParameter("MerchantId", merchantId) :
                new ObjectParameter("MerchantId", typeof(int));
    
            var orderTokenParameter = orderToken.HasValue ?
                new ObjectParameter("OrderToken", orderToken) :
                new ObjectParameter("OrderToken", typeof(System.Guid));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(int));
    
            var commentParameter = comment != null ?
                new ObjectParameter("Comment", comment) :
                new ObjectParameter("Comment", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddHistorycalDataFromOrders", merchantIdParameter, orderTokenParameter, statusParameter, commentParameter);
        }
    
        public virtual int AddMerchant(string merchantName, string merchantPhone, string merchantAddress, string merchantCallBackAddress, string userId, string userGuid, Nullable<bool> isSandingBox, string publicTokenKey, string privateToken, string merchantAlias, ObjectParameter iD)
        {
            var merchantNameParameter = merchantName != null ?
                new ObjectParameter("MerchantName", merchantName) :
                new ObjectParameter("MerchantName", typeof(string));
    
            var merchantPhoneParameter = merchantPhone != null ?
                new ObjectParameter("MerchantPhone", merchantPhone) :
                new ObjectParameter("MerchantPhone", typeof(string));
    
            var merchantAddressParameter = merchantAddress != null ?
                new ObjectParameter("MerchantAddress", merchantAddress) :
                new ObjectParameter("MerchantAddress", typeof(string));
    
            var merchantCallBackAddressParameter = merchantCallBackAddress != null ?
                new ObjectParameter("MerchantCallBackAddress", merchantCallBackAddress) :
                new ObjectParameter("MerchantCallBackAddress", typeof(string));
    
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            var userGuidParameter = userGuid != null ?
                new ObjectParameter("UserGuid", userGuid) :
                new ObjectParameter("UserGuid", typeof(string));
    
            var isSandingBoxParameter = isSandingBox.HasValue ?
                new ObjectParameter("IsSandingBox", isSandingBox) :
                new ObjectParameter("IsSandingBox", typeof(bool));
    
            var publicTokenKeyParameter = publicTokenKey != null ?
                new ObjectParameter("PublicTokenKey", publicTokenKey) :
                new ObjectParameter("PublicTokenKey", typeof(string));
    
            var privateTokenParameter = privateToken != null ?
                new ObjectParameter("PrivateToken", privateToken) :
                new ObjectParameter("PrivateToken", typeof(string));
    
            var merchantAliasParameter = merchantAlias != null ?
                new ObjectParameter("MerchantAlias", merchantAlias) :
                new ObjectParameter("MerchantAlias", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddMerchant", merchantNameParameter, merchantPhoneParameter, merchantAddressParameter, merchantCallBackAddressParameter, userIdParameter, userGuidParameter, isSandingBoxParameter, publicTokenKeyParameter, privateTokenParameter, merchantAliasParameter, iD);
        }
    
        public virtual int AddOrderHistoryRecs(Nullable<System.Guid> orderToken, Nullable<int> statusState, string comment, Nullable<int> merchantId, string aliasName)
        {
            var orderTokenParameter = orderToken.HasValue ?
                new ObjectParameter("OrderToken", orderToken) :
                new ObjectParameter("OrderToken", typeof(System.Guid));
    
            var statusStateParameter = statusState.HasValue ?
                new ObjectParameter("StatusState", statusState) :
                new ObjectParameter("StatusState", typeof(int));
    
            var commentParameter = comment != null ?
                new ObjectParameter("Comment", comment) :
                new ObjectParameter("Comment", typeof(string));
    
            var merchantIdParameter = merchantId.HasValue ?
                new ObjectParameter("MerchantId", merchantId) :
                new ObjectParameter("MerchantId", typeof(int));
    
            var aliasNameParameter = aliasName != null ?
                new ObjectParameter("AliasName", aliasName) :
                new ObjectParameter("AliasName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddOrderHistoryRecs", orderTokenParameter, statusStateParameter, commentParameter, merchantIdParameter, aliasNameParameter);
        }
    
        public virtual int AddOrUpdateAdmin(Nullable<int> admLinkId, string admUserName, string admFirstName, string admLastName, string admEmail, string admLinkAddress, string admLinkPassword, ObjectParameter admLinkOutId)
        {
            var admLinkIdParameter = admLinkId.HasValue ?
                new ObjectParameter("admLinkId", admLinkId) :
                new ObjectParameter("admLinkId", typeof(int));
    
            var admUserNameParameter = admUserName != null ?
                new ObjectParameter("admUserName", admUserName) :
                new ObjectParameter("admUserName", typeof(string));
    
            var admFirstNameParameter = admFirstName != null ?
                new ObjectParameter("admFirstName", admFirstName) :
                new ObjectParameter("admFirstName", typeof(string));
    
            var admLastNameParameter = admLastName != null ?
                new ObjectParameter("admLastName", admLastName) :
                new ObjectParameter("admLastName", typeof(string));
    
            var admEmailParameter = admEmail != null ?
                new ObjectParameter("admEmail", admEmail) :
                new ObjectParameter("admEmail", typeof(string));
    
            var admLinkAddressParameter = admLinkAddress != null ?
                new ObjectParameter("admLinkAddress", admLinkAddress) :
                new ObjectParameter("admLinkAddress", typeof(string));
    
            var admLinkPasswordParameter = admLinkPassword != null ?
                new ObjectParameter("admLinkPassword", admLinkPassword) :
                new ObjectParameter("admLinkPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddOrUpdateAdmin", admLinkIdParameter, admUserNameParameter, admFirstNameParameter, admLastNameParameter, admEmailParameter, admLinkAddressParameter, admLinkPasswordParameter, admLinkOutId);
        }
    
        public virtual int AddOrUpdateReferalLink(Nullable<int> refLinkId, string refLinkText, ObjectParameter refLinkOutId)
        {
            var refLinkIdParameter = refLinkId.HasValue ?
                new ObjectParameter("refLinkId", refLinkId) :
                new ObjectParameter("refLinkId", typeof(int));
    
            var refLinkTextParameter = refLinkText != null ?
                new ObjectParameter("refLinkText", refLinkText) :
                new ObjectParameter("refLinkText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddOrUpdateReferalLink", refLinkIdParameter, refLinkTextParameter, refLinkOutId);
        }
    
        public virtual int AddOrUpdateSharedPhoto(string paymentId, string comment, ObjectParameter photoId)
        {
            var paymentIdParameter = paymentId != null ?
                new ObjectParameter("PaymentId", paymentId) :
                new ObjectParameter("PaymentId", typeof(string));
    
            var commentParameter = comment != null ?
                new ObjectParameter("Comment", comment) :
                new ObjectParameter("Comment", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddOrUpdateSharedPhoto", paymentIdParameter, commentParameter, photoId);
        }
    
        public virtual int AddProofDoc(string custName, string bankName, string lastFourDigits, string other, string fileName, string filePath, Nullable<int> bankCcyId, Nullable<System.DateTime> paymentDate, Nullable<decimal> amount, Nullable<int> depositId, Nullable<int> proofDocId)
        {
            var custNameParameter = custName != null ?
                new ObjectParameter("custName", custName) :
                new ObjectParameter("custName", typeof(string));
    
            var bankNameParameter = bankName != null ?
                new ObjectParameter("bankName", bankName) :
                new ObjectParameter("bankName", typeof(string));
    
            var lastFourDigitsParameter = lastFourDigits != null ?
                new ObjectParameter("lastFourDigits", lastFourDigits) :
                new ObjectParameter("lastFourDigits", typeof(string));
    
            var otherParameter = other != null ?
                new ObjectParameter("other", other) :
                new ObjectParameter("other", typeof(string));
    
            var fileNameParameter = fileName != null ?
                new ObjectParameter("fileName", fileName) :
                new ObjectParameter("fileName", typeof(string));
    
            var filePathParameter = filePath != null ?
                new ObjectParameter("filePath", filePath) :
                new ObjectParameter("filePath", typeof(string));
    
            var bankCcyIdParameter = bankCcyId.HasValue ?
                new ObjectParameter("bankCcyId", bankCcyId) :
                new ObjectParameter("bankCcyId", typeof(int));
    
            var paymentDateParameter = paymentDate.HasValue ?
                new ObjectParameter("paymentDate", paymentDate) :
                new ObjectParameter("paymentDate", typeof(System.DateTime));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("amount", amount) :
                new ObjectParameter("amount", typeof(decimal));
    
            var depositIdParameter = depositId.HasValue ?
                new ObjectParameter("depositId", depositId) :
                new ObjectParameter("depositId", typeof(int));
    
            var proofDocIdParameter = proofDocId.HasValue ?
                new ObjectParameter("proofDocId", proofDocId) :
                new ObjectParameter("proofDocId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddProofDoc", custNameParameter, bankNameParameter, lastFourDigitsParameter, otherParameter, fileNameParameter, filePathParameter, bankCcyIdParameter, paymentDateParameter, amountParameter, depositIdParameter, proofDocIdParameter);
        }
    
        public virtual int AddSendedMail(Nullable<int> depID, string mailFrom, string mailText, string mailSubject, byte[] mailAttachment, string siteCategory)
        {
            var depIDParameter = depID.HasValue ?
                new ObjectParameter("DepID", depID) :
                new ObjectParameter("DepID", typeof(int));
    
            var mailFromParameter = mailFrom != null ?
                new ObjectParameter("MailFrom", mailFrom) :
                new ObjectParameter("MailFrom", typeof(string));
    
            var mailTextParameter = mailText != null ?
                new ObjectParameter("MailText", mailText) :
                new ObjectParameter("MailText", typeof(string));
    
            var mailSubjectParameter = mailSubject != null ?
                new ObjectParameter("MailSubject", mailSubject) :
                new ObjectParameter("MailSubject", typeof(string));
    
            var mailAttachmentParameter = mailAttachment != null ?
                new ObjectParameter("MailAttachment", mailAttachment) :
                new ObjectParameter("MailAttachment", typeof(byte[]));
    
            var siteCategoryParameter = siteCategory != null ?
                new ObjectParameter("SiteCategory", siteCategory) :
                new ObjectParameter("SiteCategory", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddSendedMail", depIDParameter, mailFromParameter, mailTextParameter, mailSubjectParameter, mailAttachmentParameter, siteCategoryParameter);
        }
    
        public virtual int AddUser(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddUser", usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<System.DateTime>> AddUserToken(string userName, string password, string userId, string tokenKey, string tokenId, Nullable<System.DateTime> creationDate, ObjectParameter expiredDate)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            var tokenKeyParameter = tokenKey != null ?
                new ObjectParameter("TokenKey", tokenKey) :
                new ObjectParameter("TokenKey", typeof(string));
    
            var tokenIdParameter = tokenId != null ?
                new ObjectParameter("TokenId", tokenId) :
                new ObjectParameter("TokenId", typeof(string));
    
            var creationDateParameter = creationDate.HasValue ?
                new ObjectParameter("CreationDate", creationDate) :
                new ObjectParameter("CreationDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.DateTime>>("AddUserToken", userNameParameter, passwordParameter, userIdParameter, tokenKeyParameter, tokenIdParameter, creationDateParameter, expiredDate);
        }
    
        public virtual int AddWelcomeMessage(string wlcMsgText, string username, string wlcMsgTextRu, string wlcMsgTextFr, string wlcMsgTextPh)
        {
            var wlcMsgTextParameter = wlcMsgText != null ?
                new ObjectParameter("wlcMsgText", wlcMsgText) :
                new ObjectParameter("wlcMsgText", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var wlcMsgTextRuParameter = wlcMsgTextRu != null ?
                new ObjectParameter("wlcMsgTextRu", wlcMsgTextRu) :
                new ObjectParameter("wlcMsgTextRu", typeof(string));
    
            var wlcMsgTextFrParameter = wlcMsgTextFr != null ?
                new ObjectParameter("wlcMsgTextFr", wlcMsgTextFr) :
                new ObjectParameter("wlcMsgTextFr", typeof(string));
    
            var wlcMsgTextPhParameter = wlcMsgTextPh != null ?
                new ObjectParameter("wlcMsgTextPh", wlcMsgTextPh) :
                new ObjectParameter("wlcMsgTextPh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddWelcomeMessage", wlcMsgTextParameter, usernameParameter, wlcMsgTextRuParameter, wlcMsgTextFrParameter, wlcMsgTextPhParameter);
        }
    
        public virtual int AddWireInstruction(string wireInstText, Nullable<int> bankCcyId)
        {
            var wireInstTextParameter = wireInstText != null ?
                new ObjectParameter("wireInstText", wireInstText) :
                new ObjectParameter("wireInstText", typeof(string));
    
            var bankCcyIdParameter = bankCcyId.HasValue ?
                new ObjectParameter("bankCcyId", bankCcyId) :
                new ObjectParameter("bankCcyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddWireInstruction", wireInstTextParameter, bankCcyIdParameter);
        }
    
        public virtual int ChangePassword(string username, string hashedPassword)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var hashedPasswordParameter = hashedPassword != null ?
                new ObjectParameter("hashedPassword", hashedPassword) :
                new ObjectParameter("hashedPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ChangePassword", usernameParameter, hashedPasswordParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> CheckMerchantIfExist(string merchantSecKey, string merchantTokenKey)
        {
            var merchantSecKeyParameter = merchantSecKey != null ?
                new ObjectParameter("merchantSecKey", merchantSecKey) :
                new ObjectParameter("merchantSecKey", typeof(string));
    
            var merchantTokenKeyParameter = merchantTokenKey != null ?
                new ObjectParameter("merchantTokenKey", merchantTokenKey) :
                new ObjectParameter("merchantTokenKey", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("CheckMerchantIfExist", merchantSecKeyParameter, merchantTokenKeyParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> CheckOrderIfExist(Nullable<System.Guid> orderToken)
        {
            var orderTokenParameter = orderToken.HasValue ?
                new ObjectParameter("orderToken", orderToken) :
                new ObjectParameter("orderToken", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("CheckOrderIfExist", orderTokenParameter);
        }
    
        public virtual int DeleteBank(Nullable<int> bankId)
        {
            var bankIdParameter = bankId.HasValue ?
                new ObjectParameter("bankId", bankId) :
                new ObjectParameter("bankId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteBank", bankIdParameter);
        }
    
        public virtual int DeleteBankDeposit(Nullable<int> depositId)
        {
            var depositIdParameter = depositId.HasValue ?
                new ObjectParameter("depositId", depositId) :
                new ObjectParameter("depositId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteBankDeposit", depositIdParameter);
        }
    
        public virtual int DeleteContactUsRec(Nullable<int> contactUsId)
        {
            var contactUsIdParameter = contactUsId.HasValue ?
                new ObjectParameter("ContactUsId", contactUsId) :
                new ObjectParameter("ContactUsId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteContactUsRec", contactUsIdParameter);
        }
    
        public virtual int DeleteCurrency(Nullable<int> currId)
        {
            var currIdParameter = currId.HasValue ?
                new ObjectParameter("currId", currId) :
                new ObjectParameter("currId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteCurrency", currIdParameter);
        }
    
        public virtual int DeleteFavoriteCurrency(string iDCurrencies, string iDUser)
        {
            var iDCurrenciesParameter = iDCurrencies != null ?
                new ObjectParameter("IDCurrencies", iDCurrencies) :
                new ObjectParameter("IDCurrencies", typeof(string));
    
            var iDUserParameter = iDUser != null ?
                new ObjectParameter("IDUser", iDUser) :
                new ObjectParameter("IDUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteFavoriteCurrency", iDCurrenciesParameter, iDUserParameter);
        }
    
        public virtual int DeletePayInInstruction(Nullable<int> bankCurrencyId)
        {
            var bankCurrencyIdParameter = bankCurrencyId.HasValue ?
                new ObjectParameter("bankCurrencyId", bankCurrencyId) :
                new ObjectParameter("bankCurrencyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeletePayInInstruction", bankCurrencyIdParameter);
        }
    
        public virtual int DeleteProofDoc(Nullable<int> proofDocId)
        {
            var proofDocIdParameter = proofDocId.HasValue ?
                new ObjectParameter("proofDocId", proofDocId) :
                new ObjectParameter("proofDocId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteProofDoc", proofDocIdParameter);
        }
    
        public virtual int DeleteWelcomeMessage(Nullable<int> wlcMsgId)
        {
            var wlcMsgIdParameter = wlcMsgId.HasValue ?
                new ObjectParameter("wlcMsgId", wlcMsgId) :
                new ObjectParameter("wlcMsgId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteWelcomeMessage", wlcMsgIdParameter);
        }
    
        public virtual int DeleteWireInstruction(Nullable<int> wireInstId)
        {
            var wireInstIdParameter = wireInstId.HasValue ?
                new ObjectParameter("wireInstId", wireInstId) :
                new ObjectParameter("wireInstId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteWireInstruction", wireInstIdParameter);
        }
    
        public virtual int GenerateOrderToken(Nullable<int> merchantId, string merchantWebSite, string tokenKeysForOrders, ObjectParameter orderToken)
        {
            var merchantIdParameter = merchantId.HasValue ?
                new ObjectParameter("MerchantId", merchantId) :
                new ObjectParameter("MerchantId", typeof(int));
    
            var merchantWebSiteParameter = merchantWebSite != null ?
                new ObjectParameter("MerchantWebSite", merchantWebSite) :
                new ObjectParameter("MerchantWebSite", typeof(string));
    
            var tokenKeysForOrdersParameter = tokenKeysForOrders != null ?
                new ObjectParameter("TokenKeysForOrders", tokenKeysForOrders) :
                new ObjectParameter("TokenKeysForOrders", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GenerateOrderToken", merchantIdParameter, merchantWebSiteParameter, tokenKeysForOrdersParameter, orderToken);
        }
    
        public virtual ObjectResult<GetAdminLink_Result> GetAdminLink()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAdminLink_Result>("GetAdminLink");
        }
    
        public virtual ObjectResult<GetApiUserById_Result> GetApiUserById(string tokenKey)
        {
            var tokenKeyParameter = tokenKey != null ?
                new ObjectParameter("TokenKey", tokenKey) :
                new ObjectParameter("TokenKey", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetApiUserById_Result>("GetApiUserById", tokenKeyParameter);
        }
    
        public virtual ObjectResult<GetBankAndInstruction_Result> GetBankAndInstruction()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBankAndInstruction_Result>("GetBankAndInstruction");
        }
    
        public virtual ObjectResult<GetBankAndInstructionById_Result> GetBankAndInstructionById(Nullable<int> bankCcyId)
        {
            var bankCcyIdParameter = bankCcyId.HasValue ?
                new ObjectParameter("bankCcyId", bankCcyId) :
                new ObjectParameter("bankCcyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBankAndInstructionById_Result>("GetBankAndInstructionById", bankCcyIdParameter);
        }
    
        public virtual ObjectResult<GetBankCurrencies_Result> GetBankCurrencies()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBankCurrencies_Result>("GetBankCurrencies");
        }
    
        public virtual ObjectResult<GetBankDeposits_Result> GetBankDeposits(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBankDeposits_Result>("GetBankDeposits", usernameParameter);
        }
    
        public virtual ObjectResult<GetBanks_Result> GetBanks()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBanks_Result>("GetBanks");
        }
    
        public virtual ObjectResult<GetContactUsList_Result> GetContactUsList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetContactUsList_Result>("GetContactUsList");
        }
    
        public virtual ObjectResult<GetCountries_Result> GetCountries()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCountries_Result>("GetCountries");
        }
    
        public virtual ObjectResult<GetCurrencies_Result> GetCurrencies()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCurrencies_Result>("GetCurrencies");
        }
    
        public virtual ObjectResult<GetFavoriteCurrencyList_Result> GetFavoriteCurrencyList(string iDUser)
        {
            var iDUserParameter = iDUser != null ?
                new ObjectParameter("IDUser", iDUser) :
                new ObjectParameter("IDUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetFavoriteCurrencyList_Result>("GetFavoriteCurrencyList", iDUserParameter);
        }
    
        public virtual ObjectResult<GetFundChanges_Result> GetFundChanges()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetFundChanges_Result>("GetFundChanges");
        }
    
        public virtual ObjectResult<GetFundRequests_Result> GetFundRequests()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetFundRequests_Result>("GetFundRequests");
        }
    
        public virtual ObjectResult<GetListOfMerchants_Result> GetListOfMerchants(string userId, string userGuid)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            var userGuidParameter = userGuid != null ?
                new ObjectParameter("UserGuid", userGuid) :
                new ObjectParameter("UserGuid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetListOfMerchants_Result>("GetListOfMerchants", userIdParameter, userGuidParameter);
        }
    
        public virtual ObjectResult<string> GetMerchantName(Nullable<int> merchantId)
        {
            var merchantIdParameter = merchantId.HasValue ?
                new ObjectParameter("merchantId", merchantId) :
                new ObjectParameter("merchantId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetMerchantName", merchantIdParameter);
        }
    
        public virtual ObjectResult<GetProofDocById_Result> GetProofDocById(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProofDocById_Result>("GetProofDocById", iDParameter);
        }
    
        public virtual ObjectResult<GetReferalLinksList_Result> GetReferalLinksList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetReferalLinksList_Result>("GetReferalLinksList");
        }
    
        public virtual int GetSharedPhoto(string paymentId, ObjectParameter photoId, ObjectParameter expiredDate)
        {
            var paymentIdParameter = paymentId != null ?
                new ObjectParameter("PaymentId", paymentId) :
                new ObjectParameter("PaymentId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetSharedPhoto", paymentIdParameter, photoId, expiredDate);
        }
    
        public virtual int GetStatusChangeHistory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetStatusChangeHistory");
        }
    
        public virtual ObjectResult<GetUsers_Result> GetUsers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUsers_Result>("GetUsers");
        }
    
        public virtual ObjectResult<GetWelcomeMessages_Result> GetWelcomeMessages()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWelcomeMessages_Result>("GetWelcomeMessages");
        }
    
        public virtual ObjectResult<GetWireInstructions_Result> GetWireInstructions()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWireInstructions_Result>("GetWireInstructions");
        }
    
        public virtual int UpdateBank(Nullable<int> bankId, string bankName, Nullable<int> bankCountry)
        {
            var bankIdParameter = bankId.HasValue ?
                new ObjectParameter("bankId", bankId) :
                new ObjectParameter("bankId", typeof(int));
    
            var bankNameParameter = bankName != null ?
                new ObjectParameter("bankName", bankName) :
                new ObjectParameter("bankName", typeof(string));
    
            var bankCountryParameter = bankCountry.HasValue ?
                new ObjectParameter("bankCountry", bankCountry) :
                new ObjectParameter("bankCountry", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateBank", bankIdParameter, bankNameParameter, bankCountryParameter);
        }
    
        public virtual int UpdateBankCurrency(Nullable<int> bankId, Nullable<int> bCcyId, Nullable<int> ccyId, Nullable<int> wireInstId)
        {
            var bankIdParameter = bankId.HasValue ?
                new ObjectParameter("bankId", bankId) :
                new ObjectParameter("bankId", typeof(int));
    
            var bCcyIdParameter = bCcyId.HasValue ?
                new ObjectParameter("bCcyId", bCcyId) :
                new ObjectParameter("bCcyId", typeof(int));
    
            var ccyIdParameter = ccyId.HasValue ?
                new ObjectParameter("ccyId", ccyId) :
                new ObjectParameter("ccyId", typeof(int));
    
            var wireInstIdParameter = wireInstId.HasValue ?
                new ObjectParameter("wireInstId", wireInstId) :
                new ObjectParameter("wireInstId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateBankCurrency", bankIdParameter, bCcyIdParameter, ccyIdParameter, wireInstIdParameter);
        }
    
        public virtual int UpdateContactUsRec(Nullable<int> cuID, string cuName, string cuMail, Nullable<int> cuWeight)
        {
            var cuIDParameter = cuID.HasValue ?
                new ObjectParameter("cuID", cuID) :
                new ObjectParameter("cuID", typeof(int));
    
            var cuNameParameter = cuName != null ?
                new ObjectParameter("cuName", cuName) :
                new ObjectParameter("cuName", typeof(string));
    
            var cuMailParameter = cuMail != null ?
                new ObjectParameter("cuMail", cuMail) :
                new ObjectParameter("cuMail", typeof(string));
    
            var cuWeightParameter = cuWeight.HasValue ?
                new ObjectParameter("cuWeight", cuWeight) :
                new ObjectParameter("cuWeight", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateContactUsRec", cuIDParameter, cuNameParameter, cuMailParameter, cuWeightParameter);
        }
    
        public virtual int UpdateCurrency(Nullable<int> currId, string ccyName, string ccyCode, string ccySymbol)
        {
            var currIdParameter = currId.HasValue ?
                new ObjectParameter("currId", currId) :
                new ObjectParameter("currId", typeof(int));
    
            var ccyNameParameter = ccyName != null ?
                new ObjectParameter("ccyName", ccyName) :
                new ObjectParameter("ccyName", typeof(string));
    
            var ccyCodeParameter = ccyCode != null ?
                new ObjectParameter("ccyCode", ccyCode) :
                new ObjectParameter("ccyCode", typeof(string));
    
            var ccySymbolParameter = ccySymbol != null ?
                new ObjectParameter("ccySymbol", ccySymbol) :
                new ObjectParameter("ccySymbol", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateCurrency", currIdParameter, ccyNameParameter, ccyCodeParameter, ccySymbolParameter);
        }
    
        public virtual int UpdateFundRequest(Nullable<int> fndId, string newStatus, string username, string notes)
        {
            var fndIdParameter = fndId.HasValue ?
                new ObjectParameter("fndId", fndId) :
                new ObjectParameter("fndId", typeof(int));
    
            var newStatusParameter = newStatus != null ?
                new ObjectParameter("newStatus", newStatus) :
                new ObjectParameter("newStatus", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var notesParameter = notes != null ?
                new ObjectParameter("notes", notes) :
                new ObjectParameter("notes", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateFundRequest", fndIdParameter, newStatusParameter, usernameParameter, notesParameter);
        }
    
        public virtual int UpdateMerchantCallBackAddress(Nullable<System.Guid> merchantGuid, string merchantCallBackAddress)
        {
            var merchantGuidParameter = merchantGuid.HasValue ?
                new ObjectParameter("MerchantGuid", merchantGuid) :
                new ObjectParameter("MerchantGuid", typeof(System.Guid));
    
            var merchantCallBackAddressParameter = merchantCallBackAddress != null ?
                new ObjectParameter("MerchantCallBackAddress", merchantCallBackAddress) :
                new ObjectParameter("MerchantCallBackAddress", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateMerchantCallBackAddress", merchantGuidParameter, merchantCallBackAddressParameter);
        }
    
        public virtual int UpdateMerchantsRec(Nullable<int> merchantId, Nullable<System.Guid> merchantGuid, string merchantName, string merchantPhone, string merchantAddress, string merchantCallBackAddress, Nullable<bool> isSandingBox, string merchantAlias)
        {
            var merchantIdParameter = merchantId.HasValue ?
                new ObjectParameter("MerchantId", merchantId) :
                new ObjectParameter("MerchantId", typeof(int));
    
            var merchantGuidParameter = merchantGuid.HasValue ?
                new ObjectParameter("MerchantGuid", merchantGuid) :
                new ObjectParameter("MerchantGuid", typeof(System.Guid));
    
            var merchantNameParameter = merchantName != null ?
                new ObjectParameter("MerchantName", merchantName) :
                new ObjectParameter("MerchantName", typeof(string));
    
            var merchantPhoneParameter = merchantPhone != null ?
                new ObjectParameter("MerchantPhone", merchantPhone) :
                new ObjectParameter("MerchantPhone", typeof(string));
    
            var merchantAddressParameter = merchantAddress != null ?
                new ObjectParameter("MerchantAddress", merchantAddress) :
                new ObjectParameter("MerchantAddress", typeof(string));
    
            var merchantCallBackAddressParameter = merchantCallBackAddress != null ?
                new ObjectParameter("MerchantCallBackAddress", merchantCallBackAddress) :
                new ObjectParameter("MerchantCallBackAddress", typeof(string));
    
            var isSandingBoxParameter = isSandingBox.HasValue ?
                new ObjectParameter("IsSandingBox", isSandingBox) :
                new ObjectParameter("IsSandingBox", typeof(bool));
    
            var merchantAliasParameter = merchantAlias != null ?
                new ObjectParameter("MerchantAlias", merchantAlias) :
                new ObjectParameter("MerchantAlias", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateMerchantsRec", merchantIdParameter, merchantGuidParameter, merchantNameParameter, merchantPhoneParameter, merchantAddressParameter, merchantCallBackAddressParameter, isSandingBoxParameter, merchantAliasParameter);
        }
    
        public virtual int UpdateTsgIdViaTsgService(string userLogin, Nullable<System.Guid> userTokenByTSG)
        {
            var userLoginParameter = userLogin != null ?
                new ObjectParameter("userLogin", userLogin) :
                new ObjectParameter("userLogin", typeof(string));
    
            var userTokenByTSGParameter = userTokenByTSG.HasValue ?
                new ObjectParameter("userTokenByTSG", userTokenByTSG) :
                new ObjectParameter("userTokenByTSG", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTsgIdViaTsgService", userLoginParameter, userTokenByTSGParameter);
        }
    
        public virtual int UpdateUserLastLoginDate(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateUserLastLoginDate", usernameParameter);
        }
    
        public virtual int UpdateWelcomeMessage(Nullable<int> wlcMsgId, string wlcMsgText, string wlcMsgTextRu, string wlcMsgTextFr, string wlcMsgTextPh)
        {
            var wlcMsgIdParameter = wlcMsgId.HasValue ?
                new ObjectParameter("wlcMsgId", wlcMsgId) :
                new ObjectParameter("wlcMsgId", typeof(int));
    
            var wlcMsgTextParameter = wlcMsgText != null ?
                new ObjectParameter("wlcMsgText", wlcMsgText) :
                new ObjectParameter("wlcMsgText", typeof(string));
    
            var wlcMsgTextRuParameter = wlcMsgTextRu != null ?
                new ObjectParameter("wlcMsgTextRu", wlcMsgTextRu) :
                new ObjectParameter("wlcMsgTextRu", typeof(string));
    
            var wlcMsgTextFrParameter = wlcMsgTextFr != null ?
                new ObjectParameter("wlcMsgTextFr", wlcMsgTextFr) :
                new ObjectParameter("wlcMsgTextFr", typeof(string));
    
            var wlcMsgTextPhParameter = wlcMsgTextPh != null ?
                new ObjectParameter("wlcMsgTextPh", wlcMsgTextPh) :
                new ObjectParameter("wlcMsgTextPh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateWelcomeMessage", wlcMsgIdParameter, wlcMsgTextParameter, wlcMsgTextRuParameter, wlcMsgTextFrParameter, wlcMsgTextPhParameter);
        }
    
        public virtual int UpdateWireInstruction(Nullable<int> wireInstId, string wireInstText)
        {
            var wireInstIdParameter = wireInstId.HasValue ?
                new ObjectParameter("wireInstId", wireInstId) :
                new ObjectParameter("wireInstId", typeof(int));
    
            var wireInstTextParameter = wireInstText != null ?
                new ObjectParameter("wireInstText", wireInstText) :
                new ObjectParameter("wireInstText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateWireInstruction", wireInstIdParameter, wireInstTextParameter);
        }

    }
}
