//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSG.Models.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TSG.Models.App_LocalResources.GlobalModel", typeof(GlobalModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string CommonObjects_Amount {
            get {
                return ResourceManager.GetString("CommonObjects.Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string CommonObjects_CreationDate {
            get {
                return ResourceManager.GetString("CommonObjects.CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Code.
        /// </summary>
        public static string CommonObjects_CurrencyCode {
            get {
                return ResourceManager.GetString("CommonObjects.CurrencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Expire.
        /// </summary>
        public static string CommonObjects_DateOfExpire {
            get {
                return ResourceManager.GetString("CommonObjects.DateOfExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string CommonObjects_Deleted {
            get {
                return ResourceManager.GetString("CommonObjects.Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string CommonObjects_ID {
            get {
                return ResourceManager.GetString("CommonObjects.ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string CommonObjects_Info {
            get {
                return ResourceManager.GetString("CommonObjects.Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string CommonObjects_Position {
            get {
                return ResourceManager.GetString("CommonObjects.Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string CommonObjects_Price {
            get {
                return ResourceManager.GetString("CommonObjects.Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        public static string CommonObjects_Published {
            get {
                return ResourceManager.GetString("CommonObjects.Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string CommonObjects_Quantity {
            get {
                return ResourceManager.GetString("CommonObjects.Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string CommonObjects_Status {
            get {
                return ResourceManager.GetString("CommonObjects.Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        public static string CommonObjects_Timestamp {
            get {
                return ResourceManager.GetString("CommonObjects.Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Id.
        /// </summary>
        public static string DaForPaymentLimitLog_ParentId {
            get {
                return ResourceManager.GetString("DaForPaymentLimitLog.ParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All time.
        /// </summary>
        public static string DelegatedAuthoriryLimitationType_AllTime {
            get {
                return ResourceManager.GetString("DelegatedAuthoriryLimitationType.AllTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        public static string DelegatedAuthoriryLimitationType_Daily {
            get {
                return ResourceManager.GetString("DelegatedAuthoriryLimitationType.Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string DelegatedAuthoriryLimitationType_Montly {
            get {
                return ResourceManager.GetString("DelegatedAuthoriryLimitationType.Montly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction.
        /// </summary>
        public static string DelegatedAuthoriryLimitationType_Transaction {
            get {
                return ResourceManager.GetString("DelegatedAuthoriryLimitationType.Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        public static string DelegatedAuthoriryLimitationType_Weekly {
            get {
                return ResourceManager.GetString("DelegatedAuthoriryLimitationType.Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly.
        /// </summary>
        public static string DelegatedAuthoriryLimitationType_Yearly {
            get {
                return ResourceManager.GetString("DelegatedAuthoriryLimitationType.Yearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar Code.
        /// </summary>
        public static string DelegatedAuthorirySourceLimitationType_BarCode {
            get {
                return ResourceManager.GetString("DelegatedAuthorirySourceLimitationType.BarCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NFC Device.
        /// </summary>
        public static string DelegatedAuthorirySourceLimitationType_Nfc {
            get {
                return ResourceManager.GetString("DelegatedAuthorirySourceLimitationType.Nfc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR Code.
        /// </summary>
        public static string DelegatedAuthorirySourceLimitationType_QrCode {
            get {
                return ResourceManager.GetString("DelegatedAuthorirySourceLimitationType.QrCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Envelope.
        /// </summary>
        public static string DelegatedAuthorirySourceLimitationType_RedEnvelope {
            get {
                return ResourceManager.GetString("DelegatedAuthorirySourceLimitationType.RedEnvelope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret Phrase.
        /// </summary>
        public static string DelegatedAuthorirySourceLimitationType_SecretCode {
            get {
                return ResourceManager.GetString("DelegatedAuthorirySourceLimitationType.SecretCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vo2 Tech Card.
        /// </summary>
        public static string DelegatedAuthorirySourceLimitationType_Vo2TechCard {
            get {
                return ResourceManager.GetString("DelegatedAuthorirySourceLimitationType.Vo2TechCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt.
        /// </summary>
        public static string OrdersDetails_Receipt {
            get {
                return ResourceManager.GetString("OrdersDetails.Receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit Type.
        /// </summary>
        public static string PaymentLimit_LimitType {
            get {
                return ResourceManager.GetString("PaymentLimit.LimitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Of Payment Limit.
        /// </summary>
        public static string PaymentLimit_NameOfPaymentLimit {
            get {
                return ResourceManager.GetString("PaymentLimit.NameOfPaymentLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sys Name Of Payment Limit.
        /// </summary>
        public static string PaymentLimit_SysNameOfPaymentLimit {
            get {
                return ResourceManager.GetString("PaymentLimit.SysNameOfPaymentLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified Date.
        /// </summary>
        public static string QrForPaymentLimit_LastModifiedDate {
            get {
                return ResourceManager.GetString("QrForPaymentLimit.LastModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limits.
        /// </summary>
        public static string QrForPaymentLimit_Limits {
            get {
                return ResourceManager.GetString("QrForPaymentLimit.Limits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qr Code.
        /// </summary>
        public static string QrForPaymentLimit_QrCode {
            get {
                return ResourceManager.GetString("QrForPaymentLimit.QrCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qr Type.
        /// </summary>
        public static string QrForPaymentLimit_QrType {
            get {
                return ResourceManager.GetString("QrForPaymentLimit.QrType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret Phrase.
        /// </summary>
        public static string QrForPaymentLimit_SecretCode {
            get {
                return ResourceManager.GetString("QrForPaymentLimit.SecretCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string QrForPaymentLimit_SourceType {
            get {
                return ResourceManager.GetString("QrForPaymentLimit.SourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status By Limit.
        /// </summary>
        public static string QrForPaymentLimit_StatusByLimit {
            get {
                return ResourceManager.GetString("QrForPaymentLimit.StatusByLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Data.
        /// </summary>
        public static string QrForPaymentLimit_UserData {
            get {
                return ResourceManager.GetString("QrForPaymentLimit.UserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string QrForPaymentLimit_UserName {
            get {
                return ResourceManager.GetString("QrForPaymentLimit.UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Of Limit.
        /// </summary>
        public static string QrForPaymentLimitTab_TypeOfLimit {
            get {
                return ResourceManager.GetString("QrForPaymentLimitTab.TypeOfLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name.
        /// </summary>
        public static string ShopCategories_Name {
            get {
                return ResourceManager.GetString("ShopCategories.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent.
        /// </summary>
        public static string ShopCategories_Parent {
            get {
                return ResourceManager.GetString("ShopCategories.Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop name.
        /// </summary>
        public static string ShopInfo_Name {
            get {
                return ResourceManager.GetString("ShopInfo.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner WPayID.
        /// </summary>
        public static string ShopInfo_OwnerWPayID {
            get {
                return ResourceManager.GetString("ShopInfo.OwnerWPayID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop Logo.
        /// </summary>
        public static string ShopInfo_ShopLogo {
            get {
                return ResourceManager.GetString("ShopInfo.ShopLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buyer Wpay Id.
        /// </summary>
        public static string ShopOrders_BuyerWpayId {
            get {
                return ResourceManager.GetString("ShopOrders.BuyerWpayId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Id.
        /// </summary>
        public static string ShopOrdersItem_OrderId {
            get {
                return ResourceManager.GetString("ShopOrdersItem.OrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Id.
        /// </summary>
        public static string ShopOrdersItem_ProductId {
            get {
                return ResourceManager.GetString("ShopOrdersItem.ProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category ID.
        /// </summary>
        public static string ShopProduct_CategoryId {
            get {
                return ResourceManager.GetString("ShopProduct.CategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Description.
        /// </summary>
        public static string ShopProduct_FullDescription {
            get {
                return ResourceManager.GetString("ShopProduct.FullDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ShopProduct_Name {
            get {
                return ResourceManager.GetString("ShopProduct.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop Id.
        /// </summary>
        public static string ShopProduct_Parent {
            get {
                return ResourceManager.GetString("ShopProduct.Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop Id.
        /// </summary>
        public static string ShopProduct_ShopId {
            get {
                return ResourceManager.GetString("ShopProduct.ShopId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Description.
        /// </summary>
        public static string ShopProduct_ShortDescription {
            get {
                return ResourceManager.GetString("ShopProduct.ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string ShopProductImages_Path {
            get {
                return ResourceManager.GetString("ShopProductImages.Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declined.
        /// </summary>
        public static string TransferedTokenStatuses_TokenDeclined {
            get {
                return ResourceManager.GetString("TransferedTokenStatuses.TokenDeclined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string TransferedTokenStatuses_TokenPending {
            get {
                return ResourceManager.GetString("TransferedTokenStatuses.TokenPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfered.
        /// </summary>
        public static string TransferedTokenStatuses_TokenTransfered {
            get {
                return ResourceManager.GetString("TransferedTokenStatuses.TokenTransfered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Envelope.
        /// </summary>
        public static string TransfersSourceType_RedEnvelope {
            get {
                return ResourceManager.GetString("TransfersSourceType_RedEnvelope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token Transfers.
        /// </summary>
        public static string TransfersSourceType_TokenTransfers {
            get {
                return ResourceManager.GetString("TransfersSourceType.TokenTransfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        public static string TransferStatuses_RedEnvelopeAccepted {
            get {
                return ResourceManager.GetString("TransferStatuses.RedEnvelopeAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declined.
        /// </summary>
        public static string TransferStatuses_RedEnvelopeDeclined {
            get {
                return ResourceManager.GetString("TransferStatuses.RedEnvelopeDeclined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting.
        /// </summary>
        public static string TransferStatuses_RedEnvelopeWaiting {
            get {
                return ResourceManager.GetString("TransferStatuses.RedEnvelopeWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claimed.
        /// </summary>
        public static string TransferStatuses_TokenClaimed {
            get {
                return ResourceManager.GetString("TransferStatuses.TokenClaimed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declined.
        /// </summary>
        public static string TransferStatuses_TokenDeclined {
            get {
                return ResourceManager.GetString("TransferStatuses.TokenDeclined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Claimed.
        /// </summary>
        public static string TransferStatuses_TokenNotClaimed {
            get {
                return ResourceManager.GetString("TransferStatuses.TokenNotClaimed", resourceCulture);
            }
        }
    }
}
