//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSGWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersHistory
    {
        public int ID { get; set; }
        public System.Guid TokenKey { get; set; }
        public System.DateTime DateOfChanging { get; set; }
        public int StatusState { get; set; }
        public string Comment { get; set; }
        public int MerchantId { get; set; }
        public string AliasForUser { get; set; }
    
        public virtual EnumOfOrderStatuses EnumOfOrderStatuses { get; set; }
        public virtual Merchants Merchants { get; set; }
        public virtual TokenKeysForOrders TokenKeysForOrders { get; set; }
    }
}
