//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSGWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TokenKeysForOrders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TokenKeysForOrders()
        {
            this.OrdersHistory = new HashSet<OrdersHistory>();
        }
    
        public System.Guid CustomerOrderId { get; set; }
        public int CustomerOrderStatus { get; set; }
        public Nullable<int> MerchantId { get; set; }
        public Nullable<System.Guid> CustomerId { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string MerchantWebSite { get; set; }
        public Nullable<int> CustomerAccounting { get; set; }
        public Nullable<System.DateTime> OrderExpiredDate { get; set; }
        public string Stoke { get; set; }
    
        public virtual EnumOfOrderStatuses EnumOfOrderStatuses { get; set; }
        public virtual Merchants Merchants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersHistory> OrdersHistory { get; set; }
    }
}
