//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tsg.Business.Model.TSGRatesService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateCurrencyRateRequest", Namespace="http://schemas.datacontract.org/2004/07/TSGRatesService.DataContracts")]
    [System.SerializableAttribute()]
    public partial class UpdateCurrencyRateRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AskField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal BidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CCYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Ask {
            get {
                return this.AskField;
            }
            set {
                if ((this.AskField.Equals(value) != true)) {
                    this.AskField = value;
                    this.RaisePropertyChanged("Ask");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Bid {
            get {
                return this.BidField;
            }
            set {
                if ((this.BidField.Equals(value) != true)) {
                    this.BidField = value;
                    this.RaisePropertyChanged("Bid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CCY {
            get {
                return this.CCYField;
            }
            set {
                if ((object.ReferenceEquals(this.CCYField, value) != true)) {
                    this.CCYField = value;
                    this.RaisePropertyChanged("CCY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginId {
            get {
                return this.LoginIdField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginIdField, value) != true)) {
                    this.LoginIdField = value;
                    this.RaisePropertyChanged("LoginId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResponseBase", Namespace="http://schemas.datacontract.org/2004/07/TSGRatesService.DataContracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Tsg.Business.Model.TSGRatesService.UpdateLiborRatesResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Tsg.Business.Model.TSGRatesService.UpdateCurrencyRateResponse))]
    public partial class ServiceResponseBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Tsg.Business.Model.TSGRatesService.ServiceResponse ServiceResponseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Tsg.Business.Model.TSGRatesService.ServiceResponse ServiceResponse {
            get {
                return this.ServiceResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceResponseField, value) != true)) {
                    this.ServiceResponseField = value;
                    this.RaisePropertyChanged("ServiceResponse");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResponse", Namespace="http://schemas.datacontract.org/2004/07/TSGRatesService.DataContracts")]
    [System.SerializableAttribute()]
    public partial class ServiceResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasErrorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasWarningsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Tsg.Business.Model.TSGRatesService.ServiceResponseData[] ResponsesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasErrors {
            get {
                return this.HasErrorsField;
            }
            set {
                if ((this.HasErrorsField.Equals(value) != true)) {
                    this.HasErrorsField = value;
                    this.RaisePropertyChanged("HasErrors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasWarnings {
            get {
                return this.HasWarningsField;
            }
            set {
                if ((this.HasWarningsField.Equals(value) != true)) {
                    this.HasWarningsField = value;
                    this.RaisePropertyChanged("HasWarnings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Tsg.Business.Model.TSGRatesService.ServiceResponseData[] Responses {
            get {
                return this.ResponsesField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponsesField, value) != true)) {
                    this.ResponsesField = value;
                    this.RaisePropertyChanged("Responses");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateLiborRatesResponse", Namespace="http://schemas.datacontract.org/2004/07/TSGRatesService.DataContracts")]
    [System.SerializableAttribute()]
    public partial class UpdateLiborRatesResponse : Tsg.Business.Model.TSGRatesService.ServiceResponseBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateCurrencyRateResponse", Namespace="http://schemas.datacontract.org/2004/07/TSGRatesService.DataContracts")]
    [System.SerializableAttribute()]
    public partial class UpdateCurrencyRateResponse : Tsg.Business.Model.TSGRatesService.ServiceResponseBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResponseData", Namespace="http://schemas.datacontract.org/2004/07/TSGRatesService.DataContracts")]
    [System.SerializableAttribute()]
    public partial class ServiceResponseData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Tsg.Business.Model.TSGRatesService.ServiceResponseType ResponseTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FieldNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FieldValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((this.ResponseCodeField.Equals(value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Tsg.Business.Model.TSGRatesService.ServiceResponseType ResponseType {
            get {
                return this.ResponseTypeField;
            }
            set {
                if ((this.ResponseTypeField.Equals(value) != true)) {
                    this.ResponseTypeField = value;
                    this.RaisePropertyChanged("ResponseType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string MessageDetails {
            get {
                return this.MessageDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageDetailsField, value) != true)) {
                    this.MessageDetailsField = value;
                    this.RaisePropertyChanged("MessageDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string FieldName {
            get {
                return this.FieldNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldNameField, value) != true)) {
                    this.FieldNameField = value;
                    this.RaisePropertyChanged("FieldName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string FieldValue {
            get {
                return this.FieldValueField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldValueField, value) != true)) {
                    this.FieldValueField = value;
                    this.RaisePropertyChanged("FieldValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResponseType", Namespace="http://schemas.datacontract.org/2004/07/TSGRatesService.DataTypes")]
    public enum ServiceResponseType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Information = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Validation = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateLiborRatesRequest", Namespace="http://schemas.datacontract.org/2004/07/TSGRatesService.DataContracts")]
    [System.SerializableAttribute()]
    public partial class UpdateLiborRatesRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CCYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal M1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal M12Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal M2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal M3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal M6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal M9Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal W1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CCY {
            get {
                return this.CCYField;
            }
            set {
                if ((object.ReferenceEquals(this.CCYField, value) != true)) {
                    this.CCYField = value;
                    this.RaisePropertyChanged("CCY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginId {
            get {
                return this.LoginIdField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginIdField, value) != true)) {
                    this.LoginIdField = value;
                    this.RaisePropertyChanged("LoginId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal M1 {
            get {
                return this.M1Field;
            }
            set {
                if ((this.M1Field.Equals(value) != true)) {
                    this.M1Field = value;
                    this.RaisePropertyChanged("M1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal M12 {
            get {
                return this.M12Field;
            }
            set {
                if ((this.M12Field.Equals(value) != true)) {
                    this.M12Field = value;
                    this.RaisePropertyChanged("M12");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal M2 {
            get {
                return this.M2Field;
            }
            set {
                if ((this.M2Field.Equals(value) != true)) {
                    this.M2Field = value;
                    this.RaisePropertyChanged("M2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal M3 {
            get {
                return this.M3Field;
            }
            set {
                if ((this.M3Field.Equals(value) != true)) {
                    this.M3Field = value;
                    this.RaisePropertyChanged("M3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal M6 {
            get {
                return this.M6Field;
            }
            set {
                if ((this.M6Field.Equals(value) != true)) {
                    this.M6Field = value;
                    this.RaisePropertyChanged("M6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal M9 {
            get {
                return this.M9Field;
            }
            set {
                if ((this.M9Field.Equals(value) != true)) {
                    this.M9Field = value;
                    this.RaisePropertyChanged("M9");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal W1 {
            get {
                return this.W1Field;
            }
            set {
                if ((this.W1Field.Equals(value) != true)) {
                    this.W1Field = value;
                    this.RaisePropertyChanged("W1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tradesolutionsgroup.com/services", ConfigurationName="TSGRatesService.ITsgRatesService1")]
    public interface ITsgRatesService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tradesolutionsgroup.com/services/ITsgRatesService1/GetLibraryVersion", ReplyAction="http://tradesolutionsgroup.com/services/ITsgRatesService1/GetLibraryVersionRespon" +
            "se")]
        string GetLibraryVersion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tradesolutionsgroup.com/services/ITsgRatesService1/GetLibraryVersion", ReplyAction="http://tradesolutionsgroup.com/services/ITsgRatesService1/GetLibraryVersionRespon" +
            "se")]
        System.Threading.Tasks.Task<string> GetLibraryVersionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tradesolutionsgroup.com/services/ITsgRatesService1/UpdateCurrencyRate", ReplyAction="http://tradesolutionsgroup.com/services/ITsgRatesService1/UpdateCurrencyRateRespo" +
            "nse")]
        Tsg.Business.Model.TSGRatesService.UpdateCurrencyRateResponse UpdateCurrencyRate(Tsg.Business.Model.TSGRatesService.UpdateCurrencyRateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tradesolutionsgroup.com/services/ITsgRatesService1/UpdateCurrencyRate", ReplyAction="http://tradesolutionsgroup.com/services/ITsgRatesService1/UpdateCurrencyRateRespo" +
            "nse")]
        System.Threading.Tasks.Task<Tsg.Business.Model.TSGRatesService.UpdateCurrencyRateResponse> UpdateCurrencyRateAsync(Tsg.Business.Model.TSGRatesService.UpdateCurrencyRateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tradesolutionsgroup.com/services/ITsgRatesService1/UpdateLiborRates", ReplyAction="http://tradesolutionsgroup.com/services/ITsgRatesService1/UpdateLiborRatesRespons" +
            "e")]
        Tsg.Business.Model.TSGRatesService.UpdateLiborRatesResponse UpdateLiborRates(Tsg.Business.Model.TSGRatesService.UpdateLiborRatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tradesolutionsgroup.com/services/ITsgRatesService1/UpdateLiborRates", ReplyAction="http://tradesolutionsgroup.com/services/ITsgRatesService1/UpdateLiborRatesRespons" +
            "e")]
        System.Threading.Tasks.Task<Tsg.Business.Model.TSGRatesService.UpdateLiborRatesResponse> UpdateLiborRatesAsync(Tsg.Business.Model.TSGRatesService.UpdateLiborRatesRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITsgRatesService1Channel : Tsg.Business.Model.TSGRatesService.ITsgRatesService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TsgRatesService1Client : System.ServiceModel.ClientBase<Tsg.Business.Model.TSGRatesService.ITsgRatesService1>, Tsg.Business.Model.TSGRatesService.ITsgRatesService1 {
        
        public TsgRatesService1Client() {
        }
        
        public TsgRatesService1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TsgRatesService1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TsgRatesService1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TsgRatesService1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetLibraryVersion() {
            return base.Channel.GetLibraryVersion();
        }
        
        public System.Threading.Tasks.Task<string> GetLibraryVersionAsync() {
            return base.Channel.GetLibraryVersionAsync();
        }
        
        public Tsg.Business.Model.TSGRatesService.UpdateCurrencyRateResponse UpdateCurrencyRate(Tsg.Business.Model.TSGRatesService.UpdateCurrencyRateRequest request) {
            return base.Channel.UpdateCurrencyRate(request);
        }
        
        public System.Threading.Tasks.Task<Tsg.Business.Model.TSGRatesService.UpdateCurrencyRateResponse> UpdateCurrencyRateAsync(Tsg.Business.Model.TSGRatesService.UpdateCurrencyRateRequest request) {
            return base.Channel.UpdateCurrencyRateAsync(request);
        }
        
        public Tsg.Business.Model.TSGRatesService.UpdateLiborRatesResponse UpdateLiborRates(Tsg.Business.Model.TSGRatesService.UpdateLiborRatesRequest request) {
            return base.Channel.UpdateLiborRates(request);
        }
        
        public System.Threading.Tasks.Task<Tsg.Business.Model.TSGRatesService.UpdateLiborRatesResponse> UpdateLiborRatesAsync(Tsg.Business.Model.TSGRatesService.UpdateLiborRatesRequest request) {
            return base.Channel.UpdateLiborRatesAsync(request);
        }
    }
}
