//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSGWebApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TsgEwalletDbEntities : DbContext
    {
        public TsgEwalletDbEntities()
            : base("name=TsgEwalletDbEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EnumOfOrderStatuses> EnumOfOrderStatuses { get; set; }
        public virtual DbSet<Merchants> Merchants { get; set; }
        public virtual DbSet<OrdersHistory> OrdersHistory { get; set; }
        public virtual DbSet<TokenKeysForOrders> TokenKeysForOrders { get; set; }
        public virtual DbSet<User> User { get; set; }
    
        public virtual int AddBank(string bankName, Nullable<int> bankCountry, ObjectParameter bankId)
        {
            var bankNameParameter = bankName != null ?
                new ObjectParameter("bankName", bankName) :
                new ObjectParameter("bankName", typeof(string));
    
            var bankCountryParameter = bankCountry.HasValue ?
                new ObjectParameter("bankCountry", bankCountry) :
                new ObjectParameter("bankCountry", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddBank", bankNameParameter, bankCountryParameter, bankId);
        }
    
        public virtual int AddBankDeposit(Nullable<decimal> fndAmt, string username, Nullable<int> bankCcyId, ObjectParameter insId)
        {
            var fndAmtParameter = fndAmt.HasValue ?
                new ObjectParameter("fndAmt", fndAmt) :
                new ObjectParameter("fndAmt", typeof(decimal));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var bankCcyIdParameter = bankCcyId.HasValue ?
                new ObjectParameter("bankCcyId", bankCcyId) :
                new ObjectParameter("bankCcyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddBankDeposit", fndAmtParameter, usernameParameter, bankCcyIdParameter, insId);
        }
    
        public virtual int AddProofDoc(string custName, string bankName, string lastFourDigits, string other, string fileName, string filePath, Nullable<int> bankCcyId, Nullable<System.DateTime> paymentDate, Nullable<decimal> amount, Nullable<int> depositId, Nullable<int> proofDocId)
        {
            var custNameParameter = custName != null ?
                new ObjectParameter("custName", custName) :
                new ObjectParameter("custName", typeof(string));
    
            var bankNameParameter = bankName != null ?
                new ObjectParameter("bankName", bankName) :
                new ObjectParameter("bankName", typeof(string));
    
            var lastFourDigitsParameter = lastFourDigits != null ?
                new ObjectParameter("lastFourDigits", lastFourDigits) :
                new ObjectParameter("lastFourDigits", typeof(string));
    
            var otherParameter = other != null ?
                new ObjectParameter("other", other) :
                new ObjectParameter("other", typeof(string));
    
            var fileNameParameter = fileName != null ?
                new ObjectParameter("fileName", fileName) :
                new ObjectParameter("fileName", typeof(string));
    
            var filePathParameter = filePath != null ?
                new ObjectParameter("filePath", filePath) :
                new ObjectParameter("filePath", typeof(string));
    
            var bankCcyIdParameter = bankCcyId.HasValue ?
                new ObjectParameter("bankCcyId", bankCcyId) :
                new ObjectParameter("bankCcyId", typeof(int));
    
            var paymentDateParameter = paymentDate.HasValue ?
                new ObjectParameter("paymentDate", paymentDate) :
                new ObjectParameter("paymentDate", typeof(System.DateTime));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("amount", amount) :
                new ObjectParameter("amount", typeof(decimal));
    
            var depositIdParameter = depositId.HasValue ?
                new ObjectParameter("depositId", depositId) :
                new ObjectParameter("depositId", typeof(int));
    
            var proofDocIdParameter = proofDocId.HasValue ?
                new ObjectParameter("proofDocId", proofDocId) :
                new ObjectParameter("proofDocId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddProofDoc", custNameParameter, bankNameParameter, lastFourDigitsParameter, otherParameter, fileNameParameter, filePathParameter, bankCcyIdParameter, paymentDateParameter, amountParameter, depositIdParameter, proofDocIdParameter);
        }
    
        public virtual int AddUser(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddUser", usernameParameter);
        }
    
        public virtual int AddWelcomeMessage(string wlcMsgText, string username)
        {
            var wlcMsgTextParameter = wlcMsgText != null ?
                new ObjectParameter("wlcMsgText", wlcMsgText) :
                new ObjectParameter("wlcMsgText", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddWelcomeMessage", wlcMsgTextParameter, usernameParameter);
        }
    
        public virtual int AddWireInstruction(string wireInstText, Nullable<int> bankCcyId)
        {
            var wireInstTextParameter = wireInstText != null ?
                new ObjectParameter("wireInstText", wireInstText) :
                new ObjectParameter("wireInstText", typeof(string));
    
            var bankCcyIdParameter = bankCcyId.HasValue ?
                new ObjectParameter("bankCcyId", bankCcyId) :
                new ObjectParameter("bankCcyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddWireInstruction", wireInstTextParameter, bankCcyIdParameter);
        }
    
        public virtual int ChangePassword(string username, string hashedPassword)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var hashedPasswordParameter = hashedPassword != null ?
                new ObjectParameter("hashedPassword", hashedPassword) :
                new ObjectParameter("hashedPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ChangePassword", usernameParameter, hashedPasswordParameter);
        }
    
        public virtual int DeleteBank(Nullable<int> bankId)
        {
            var bankIdParameter = bankId.HasValue ?
                new ObjectParameter("bankId", bankId) :
                new ObjectParameter("bankId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteBank", bankIdParameter);
        }
    
        public virtual int DeleteBankDeposit(Nullable<int> depositId)
        {
            var depositIdParameter = depositId.HasValue ?
                new ObjectParameter("depositId", depositId) :
                new ObjectParameter("depositId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteBankDeposit", depositIdParameter);
        }
    
        public virtual int DeleteProofDoc(Nullable<int> proofDocId)
        {
            var proofDocIdParameter = proofDocId.HasValue ?
                new ObjectParameter("proofDocId", proofDocId) :
                new ObjectParameter("proofDocId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteProofDoc", proofDocIdParameter);
        }
    
        public virtual int DeleteWelcomeMessage(Nullable<int> wlcMsgId)
        {
            var wlcMsgIdParameter = wlcMsgId.HasValue ?
                new ObjectParameter("wlcMsgId", wlcMsgId) :
                new ObjectParameter("wlcMsgId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteWelcomeMessage", wlcMsgIdParameter);
        }
    
        public virtual int DeleteWireInstruction(Nullable<int> wireInstId)
        {
            var wireInstIdParameter = wireInstId.HasValue ?
                new ObjectParameter("wireInstId", wireInstId) :
                new ObjectParameter("wireInstId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteWireInstruction", wireInstIdParameter);
        }
    
        public virtual ObjectResult<GetBankCurrencies_Result> GetBankCurrencies()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBankCurrencies_Result>("GetBankCurrencies");
        }
    
        public virtual ObjectResult<GetBankDeposits_Result> GetBankDeposits(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBankDeposits_Result>("GetBankDeposits", usernameParameter);
        }
    
        public virtual ObjectResult<GetBanks_Result> GetBanks()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBanks_Result>("GetBanks");
        }
    
        public virtual ObjectResult<GetCurrencies_Result> GetCurrencies()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCurrencies_Result>("GetCurrencies");
        }
    
        public virtual ObjectResult<GetFundRequests_Result> GetFundRequests()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetFundRequests_Result>("GetFundRequests");
        }
    
        public virtual ObjectResult<GetUsers_Result> GetUsers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUsers_Result>("GetUsers");
        }
    
        public virtual ObjectResult<GetWelcomeMessages_Result> GetWelcomeMessages()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWelcomeMessages_Result>("GetWelcomeMessages");
        }
    
        public virtual ObjectResult<GetWireInstructions_Result> GetWireInstructions()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWireInstructions_Result>("GetWireInstructions");
        }
    
        public virtual int UpdateBank(Nullable<int> bankId, string bankName, Nullable<int> bankCountry)
        {
            var bankIdParameter = bankId.HasValue ?
                new ObjectParameter("bankId", bankId) :
                new ObjectParameter("bankId", typeof(int));
    
            var bankNameParameter = bankName != null ?
                new ObjectParameter("bankName", bankName) :
                new ObjectParameter("bankName", typeof(string));
    
            var bankCountryParameter = bankCountry.HasValue ?
                new ObjectParameter("bankCountry", bankCountry) :
                new ObjectParameter("bankCountry", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateBank", bankIdParameter, bankNameParameter, bankCountryParameter);
        }
    
        public virtual int UpdateFundRequest(Nullable<int> fndId, string newStatus, string username, string notes)
        {
            var fndIdParameter = fndId.HasValue ?
                new ObjectParameter("fndId", fndId) :
                new ObjectParameter("fndId", typeof(int));
    
            var newStatusParameter = newStatus != null ?
                new ObjectParameter("newStatus", newStatus) :
                new ObjectParameter("newStatus", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var notesParameter = notes != null ?
                new ObjectParameter("notes", notes) :
                new ObjectParameter("notes", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateFundRequest", fndIdParameter, newStatusParameter, usernameParameter, notesParameter);
        }
    
        public virtual int UpdateUserLastLoginDate(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateUserLastLoginDate", usernameParameter);
        }
    
        public virtual int UpdateWelcomeMessage(Nullable<int> wlcMsgId, string wlcMsgText)
        {
            var wlcMsgIdParameter = wlcMsgId.HasValue ?
                new ObjectParameter("wlcMsgId", wlcMsgId) :
                new ObjectParameter("wlcMsgId", typeof(int));
    
            var wlcMsgTextParameter = wlcMsgText != null ?
                new ObjectParameter("wlcMsgText", wlcMsgText) :
                new ObjectParameter("wlcMsgText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateWelcomeMessage", wlcMsgIdParameter, wlcMsgTextParameter);
        }
    
        public virtual int UpdateWireInstruction(Nullable<int> wireInstId, string wireInstText)
        {
            var wireInstIdParameter = wireInstId.HasValue ?
                new ObjectParameter("wireInstId", wireInstId) :
                new ObjectParameter("wireInstId", typeof(int));
    
            var wireInstTextParameter = wireInstText != null ?
                new ObjectParameter("wireInstText", wireInstText) :
                new ObjectParameter("wireInstText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateWireInstruction", wireInstIdParameter, wireInstTextParameter);
        }
    }
}
