//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSGWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string username { get; set; }
        public string password { get; set; }
        public string KYCLink { get; set; }
        public Nullable<int> wlcMsgId { get; set; }
        public Nullable<System.DateTime> lastLoginDate { get; set; }
        public Nullable<bool> isLocal { get; set; }
        public Nullable<System.DateTime> curLoginDate { get; set; }
        public Nullable<int> roleId { get; set; }
        public Nullable<System.Guid> userIdByTSG { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string userMail { get; set; }
    }
}
