//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinstantPayDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnonimMail
    {
        public int ID { get; set; }
        public string MailFrom { get; set; }
        public string MailSubject { get; set; }
        public string MailNotes { get; set; }
        public string UserIpInRequest { get; set; }
        public System.DateTime DateSending { get; set; }
        public string BrowserName { get; set; }
        public string BrowserVersion { get; set; }
        public Nullable<bool> IsMobile { get; set; }
    }
}
