//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinstantPayDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conversion
    {
        public int convId { get; set; }
        public Nullable<int> fromCcyId { get; set; }
        public Nullable<int> toCcyId { get; set; }
        public Nullable<decimal> convAmt { get; set; }
        public Nullable<System.DateTime> convDate { get; set; }
        public Nullable<decimal> exchangeRate { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Currency Currency1 { get; set; }
    }
}
