//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinstantPayDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funding
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Funding()
        {
            this.FundChanges = new HashSet<FundChanges>();
        }
    
        public int fndId { get; set; }
        public Nullable<decimal> fndAmt { get; set; }
        public Nullable<System.DateTime> fndCreateDate { get; set; }
        public string username { get; set; }
        public string fndStatus { get; set; }
        public Nullable<int> bankCcyId { get; set; }
        public Nullable<System.DateTime> fndApprovedDate { get; set; }
        public Nullable<int> proofDocId { get; set; }
        public Nullable<int> fundChangeId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual BankCurrency BankCurrency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FundChanges> FundChanges { get; set; }
        public virtual ProofDoc ProofDoc { get; set; }
        public virtual User User { get; set; }
    }
}
