//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinstantPayDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class FundChanges
    {
        public int fndStatChangeId { get; set; }
        public Nullable<int> fndId { get; set; }
        public string fromStatus { get; set; }
        public string toStatus { get; set; }
        public Nullable<System.DateTime> changedDate { get; set; }
        public string changedBy { get; set; }
        public string notes { get; set; }
    
        public virtual Funding Funding { get; set; }
    }
}
