//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinstantPayDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Merchants
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Merchants()
        {
            this.OrdersHistory = new HashSet<OrdersHistory>();
            this.TokenKeysForOrders = new HashSet<TokenKeysForOrders>();
        }
    
        public int ID { get; set; }
        public System.Guid UniqueID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string UserId { get; set; }
        public string UserGuid { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string CallBackAddress { get; set; }
        public Nullable<bool> IsSandBox { get; set; }
        public string PublicTokenKey { get; set; }
        public string PrivateToken { get; set; }
        public string MerchantAlias { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersHistory> OrdersHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TokenKeysForOrders> TokenKeysForOrders { get; set; }
    }
}
