//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinstantPayDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProofDoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProofDoc()
        {
            this.Funding = new HashSet<Funding>();
        }
    
        public int proofDocId { get; set; }
        public string custName { get; set; }
        public string bankName { get; set; }
        public string lastFourDigits { get; set; }
        public string other { get; set; }
        public string fileName { get; set; }
        public string filePath { get; set; }
        public Nullable<int> bankCcyId { get; set; }
        public Nullable<System.DateTime> paymentDate { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Funding> Funding { get; set; }
    }
}
