//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinstantPayDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class SendedMails
    {
        public int ID { get; set; }
        public int DepID { get; set; }
        public string MailFrom { get; set; }
        public string MailText { get; set; }
        public string MailSubject { get; set; }
        public byte[] MailAttachment { get; set; }
        public string SiteCategory { get; set; }
    }
}
