//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinstantPayDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class WelcomeMessage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WelcomeMessage()
        {
            this.User = new HashSet<User>();
        }
    
        public int wlcMsgId { get; set; }
        public string wlcMsgText { get; set; }
        public Nullable<bool> isDefault { get; set; }
        public string wlcMsgTextRu { get; set; }
        public string wlcMsgTextFr { get; set; }
        public string wlcMsgTextPh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> User { get; set; }
    }
}
